/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ConnectionDB;
import DAO.MonAn_DAO;
import POJO.MonAn;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONDAY
 */
public class frmMonAn extends javax.swing.JFrame {

    //public static ArrayList<MonAn> dsma = MonAn_DAO.getDS_MonAn();
    /**
     * Creates new form frmMonAn
     */
    Vector tblData_MonAn = new Vector();
    Vector tblTitle_MonAn = new Vector();
    DefaultTableModel tblModel_MonAn;

    static ArrayList<MonAn> dsma = MonAn_DAO.LayThongTinMonAn();
    private frmDanhMucChucNang frmMenu;

    public frmMonAn() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Food Manager");
        hienthi_monan();
        laydulieu_monan(dsma);

    }

    public void hienthi_monan() {
        tblTitle_MonAn.add("MAMON");
        tblTitle_MonAn.add("TENMON");
        tblTitle_MonAn.add("GIATIEN");

    }

    public void laydulieu_monan(ArrayList<MonAn> dsma) {
        tblData_MonAn.removeAllElements();
        for (MonAn b : dsma) {
            Vector v = new Vector();
            v.add(b.getMaMon());
            v.add(b.getTenMon());
            v.add(b.getGiaTien());

            tblData_MonAn.add(v);
        }
        table_monan.setModel(new DefaultTableModel(tblData_MonAn, tblTitle_MonAn));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_monan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        txtGiaTienMA = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        btnRefreshDoAn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThemMA = new javax.swing.JButton();
        btnXoaMA = new javax.swing.JButton();
        btnSuaMA = new javax.swing.JButton();
        btnBackMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("QUẢN LÝ ĐỒ ĂN");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đồ ăn:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        table_monan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_monan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_monanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_monan);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã Món");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tên Món");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Giá Tiền");

        btnRefreshDoAn.setBackground(new java.awt.Color(51, 102, 255));
        btnRefreshDoAn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefreshDoAn.setForeground(new java.awt.Color(255, 255, 51));
        btnRefreshDoAn.setText("Refresh");
        btnRefreshDoAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDoAnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMon)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtGiaTienMA)))
                    .addComponent(btnRefreshDoAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGiaTienMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 204));

        btnThemMA.setBackground(new java.awt.Color(0, 204, 0));
        btnThemMA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemMA.setText("Thêm");
        btnThemMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMAActionPerformed(evt);
            }
        });

        btnXoaMA.setBackground(new java.awt.Color(0, 204, 0));
        btnXoaMA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaMA.setText("Xóa");
        btnXoaMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMAActionPerformed(evt);
            }
        });

        btnSuaMA.setBackground(new java.awt.Color(0, 204, 0));
        btnSuaMA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSuaMA.setText("Sửa");
        btnSuaMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMAActionPerformed(evt);
            }
        });

        btnBackMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnBackMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBackMenu.setForeground(new java.awt.Color(255, 255, 51));
        btnBackMenu.setText("Back");
        btnBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBackMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaMA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaMA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshDoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDoAnActionPerformed
        // TODO add your handling code here:
        ArrayList<MonAn> newDsma = MonAn_DAO.LayThongTinMonAn();

        // Xoá nội dung của các JTextField
        txtMaMon.setText("");
        txtTenMon.setText("");
        txtGiaTienMA.setText("");

        // Cập nhật danh sách món ăn
        dsma.clear();
        dsma.addAll(newDsma);

        // Làm mới bảng hiển thị
        laydulieu_monan(dsma);

        // Hiển thị thông báo cho người dùng
        JOptionPane.showMessageDialog(this, "Danh sách món ăn và các trường đã được làm mới !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshDoAnActionPerformed

    private void table_monanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_monanMouseClicked
        // TODO add your handling code here:
        // Lấy dòng (row) được chọn bằng cách sử dụng phương thức getSelectedRow
        int selectedRow = table_monan.getSelectedRow();

        if (selectedRow != -1) {
            // Lấy dữ liệu từ hàng được chọn
            String mamon = (String) table_monan.getValueAt(selectedRow, 0);
            String tenmon = (String) table_monan.getValueAt(selectedRow, 1);
            String giatien = table_monan.getValueAt(selectedRow, 2).toString();

            // Hiển thị thông tin trong các trường hoặc thực hiện các hành động khác ở đây
            // Ví dụ: hiển thị thông tin trong các JTextField
            txtMaMon.setText(mamon);
            txtTenMon.setText(tenmon);
            txtGiaTienMA.setText(giatien);
        }
    }//GEN-LAST:event_table_monanMouseClicked

    private void btnBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuActionPerformed
        // TODO add your handling code here:
        frmMenu = new frmDanhMucChucNang();
        frmMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMenuActionPerformed

    private void btnThemMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMAActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
        String mamon = txtMaMon.getText();
        String tenmon = txtTenMon.getText();
        String giatienStr = txtGiaTienMA.getText();

        // Kiểm tra tính hợp lệ của giá tiền
        double giatien = 0;
        try {
            giatien = Double.parseDouble(giatienStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ. Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ConnectionDB conn = new ConnectionDB();
            conn.GetConnect();
            Connection connection = conn.GetConnect();

            // Tạo một CallableStatement để gọi thủ tục ThemMonAn
            String sql = "{ call ThemMonAn(?, ?, ?) }";
            CallableStatement callableStatement = connection.prepareCall(sql);

            // Đặt các tham số cho thủ tục
            callableStatement.setString(1, mamon);
            callableStatement.setString(2, tenmon);
            callableStatement.setDouble(3, giatien);

            // Thực hiện thủ tục
            callableStatement.execute();

            JOptionPane.showMessageDialog(this, "Thêm món ăn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Sau khi thêm thành công, làm mới dữ liệu và xoá nội dung của các trường nhập liệu
            btnRefreshDoAnActionPerformed(evt);
            txtMaMon.setText("");
            txtTenMon.setText("");
            txtGiaTienMA.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm món ăn: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemMAActionPerformed

    private void btnXoaMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaMAActionPerformed

    private void btnSuaMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMonAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMenu;
    private javax.swing.JButton btnRefreshDoAn;
    private javax.swing.JButton btnSuaMA;
    private javax.swing.JButton btnThemMA;
    private javax.swing.JButton btnXoaMA;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_monan;
    private javax.swing.JTextField txtGiaTienMA;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
