/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author SONDAY
 */
import DAO.NhanVien_DAO;
import DAO.ConnectionDB;
import POJO.NhanVien;
import java.awt.Color;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class frmNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form frmNhanVien
     */
    Vector tblData_NhanVien = new Vector();
    Vector tblTitle_NhanVien = new Vector();
    DefaultTableModel tblModel_NhanVien;

    static ArrayList<NhanVien> dsnv = NhanVien_DAO.LayThongTinNhanVien();
    private frmDanhMucChucNang frmMenu;

    public frmNhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Employee Manager");
        hienthi_nhanvien();
        laydulieu_nhanvien(dsnv);
    }

    public void hienthi_nhanvien() {
        tblTitle_NhanVien.add("MANV");
        tblTitle_NhanVien.add("TENNV");
        tblTitle_NhanVien.add("GIOITINH");
        tblTitle_NhanVien.add("DIACHI");
        tblTitle_NhanVien.add("SODT");
        tblTitle_NhanVien.add("EMAIL");
        tblTitle_NhanVien.add("LUONG");

    }

    public void laydulieu_nhanvien(ArrayList<NhanVien> dsnv) {
        tblData_NhanVien.removeAllElements();
        for (NhanVien b : dsnv) {
            Vector v = new Vector();
            v.add(b.getManv());
            v.add(b.getTennv());
            v.add(b.getGioitinh());
            v.add(b.getDiachi());
            v.add(b.getSodt());
            v.add(b.getEmail());
            v.add(b.getLuong());

            tblData_NhanVien.add(v);
        }
        table_nv.setModel(new DefaultTableModel(tblData_NhanVien, tblTitle_NhanVien));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nv = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRefreshNV = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnBackMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhân viên:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N

        table_nv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        table_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_nvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_nv);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("MANV");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("TENNV");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("GIOITINH");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("DIACHI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("SODT");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtSoDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRefreshNV.setBackground(new java.awt.Color(51, 102, 255));
        btnRefreshNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefreshNV.setForeground(new java.awt.Color(255, 255, 51));
        btnRefreshNV.setText("Refresh");
        btnRefreshNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshNVActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("LƯƠNG");

        txtLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRefreshNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshNV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 204));

        btnThemNV.setBackground(new java.awt.Color(0, 204, 0));
        btnThemNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnXoaNV.setBackground(new java.awt.Color(0, 204, 0));
        btnXoaNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnSuaNV.setBackground(new java.awt.Color(0, 204, 0));
        btnSuaNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        btnBackMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnBackMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBackMenu.setForeground(new java.awt.Color(255, 255, 51));
        btnBackMenu.setText("Back");
        btnBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBackMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(537, 537, 537)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshNVActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu nhân viên mới từ nguồn dữ liệu (vd: cơ sở dữ liệu)
        ArrayList<NhanVien> newDsnv = NhanVien_DAO.LayThongTinNhanVien();

        // Xoá nội dung của các JTextField
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtGioiTinh.setText("");
        txtDiaChi.setText("");
        txtSoDT.setText("");
        txtEmail.setText("");
        txtLuong.setText("");

        // Cập nhật danh sách nhân viên
        dsnv.clear();
        dsnv.addAll(newDsnv);

        // Làm mới bảng hiển thị
        laydulieu_nhanvien(dsnv);

        // Hiển thị thông báo cho người dùng
        JOptionPane.showMessageDialog(this, "Danh sách nhân viên và các trường đã được làm mới !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnRefreshNVActionPerformed

    private void table_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_nvMouseClicked
        // TODO add your handling code here:
        // Lấy dòng (row) được chọn bằng cách sử dụng phương thức getSelectedRow
        int selectedRow = table_nv.getSelectedRow();

        if (selectedRow != -1) {
            // Lấy dữ liệu từ hàng được chọn
            String manv = (String) table_nv.getValueAt(selectedRow, 0);
            String tennv = (String) table_nv.getValueAt(selectedRow, 1);
            String gioitinh = (String) table_nv.getValueAt(selectedRow, 2);
            String diachi = (String) table_nv.getValueAt(selectedRow, 3);
            String sodt = (String) table_nv.getValueAt(selectedRow, 4);
            String email = (String) table_nv.getValueAt(selectedRow, 5);
            String luong = table_nv.getValueAt(selectedRow, 6).toString();

            // Hiển thị thông tin trong các trường hoặc thực hiện các hành động khác ở đây
            // Ví dụ: hiển thị thông tin trong các JTextField
            txtMaNV.setText(manv);
            txtTenNV.setText(tennv);
            txtGioiTinh.setText(gioitinh);
            txtDiaChi.setText(diachi);
            txtSoDT.setText(sodt);
            txtEmail.setText(email);
            txtLuong.setText(luong);
        }
    }//GEN-LAST:event_table_nvMouseClicked

    public boolean kiemTraRangBuoc(String manv, String luong) {
        // Kiểm tra ràng buộc cho mã nhân viên
        for (NhanVien nv : dsnv) {
            if (nv.getManv().equals(manv)) {
                int choice = JOptionPane.showOptionDialog(
                        this,
                        "Mã nhân viên đã tồn tại. Chọn tùy chọn:",
                        "Lỗi",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        new String[]{"Nhập lại", "Chỉnh sửa", "Dừng thêm"},
                        "Nhập lại");

                if (choice == 0) {
                    txtMaNV.setText(""); // Xoá mã nhân viên trong trường nhập liệu
                    return false;
                } else if (choice == 1) {
                    // Cho phép chỉnh sửa mã nhân viên
                    return false;
                } else if (choice == 2) {
                    // Dừng thêm
                    return true;
                }
            }
        }

        // Kiểm tra ràng buộc cho lương (nếu lương không phải là số)
        try {
            Double.parseDouble(luong);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lương không hợp lệ. Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        String manv = txtMaNV.getText();
        String tennv = txtTenNV.getText();
        String gioitinh = txtGioiTinh.getText();
        String diachi = txtDiaChi.getText();
        String sodt = txtSoDT.getText();
        String email = txtEmail.getText();
        String luong = txtLuong.getText();

        if (!kiemTraRangBuoc(manv, luong)) {
            return; // Không thêm nếu có lỗi
        }

        try {
            ConnectionDB conn = new ConnectionDB();
            conn.GetConnect();
            Connection connection = conn.GetConnect();

            // Create a CallableStatement to call the stored procedure
            String sql = "{ call ThemNhanVien(?, ?, ?, ?, ?, ?, ?) }";
            CallableStatement callableStatement = connection.prepareCall(sql);

            // Set the parameters for the stored procedure
            callableStatement.setString(1, manv);
            callableStatement.setString(2, tennv);
            callableStatement.setString(3, gioitinh);
            callableStatement.setString(4, diachi);
            callableStatement.setString(5, sodt);
            callableStatement.setString(6, email);
            callableStatement.setString(7, luong);

            // Execute the stored procedure
            callableStatement.execute();

            JOptionPane.showMessageDialog(this, "Thêm Nhân Viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Sau khi thêm thành công, bạn có thể làm mới dữ liệu và xoá nội dung của các trường nhập liệu
            btnRefreshNVActionPerformed(evt);
            txtMaNV.setText("");
            txtTenNV.setText("");
            txtGioiTinh.setText("");
            txtDiaChi.setText("");
            txtSoDT.setText("");
            txtEmail.setText("");
            txtLuong.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm Nhân Viên: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuActionPerformed
        // TODO add your handling code here:
        frmMenu = new frmDanhMucChucNang();
        frmMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMenuActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        // Lấy chỉ số dòng được chọn trong bảng
        int selectedRow = table_nv.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa từ bảng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy mã nhân viên từ dòng được chọn
        String manv = (String) table_nv.getValueAt(selectedRow, 0);

        // Hiển thị hộp thoại xác nhận xóa
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa nhân viên có mã " + manv + "?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            try {
                ConnectionDB conn = new ConnectionDB();
                conn.GetConnect();
                Connection connection = conn.GetConnect();

                // Tạo một câu lệnh SQL để xóa nhân viên
                String sql = "DELETE FROM NhanVien WHERE MANV = ?";
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, manv);

                // Thực hiện câu lệnh xóa
                int affectedRows = preparedStatement.executeUpdate();

                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa Nhân Viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                    // Sau khi xóa thành công, làm mới dữ liệu và xoá nội dung của các trường nhập liệu
                    btnRefreshNVActionPerformed(evt);
                    txtMaNV.setText("");
                    txtTenNV.setText("");
                    txtGioiTinh.setText("");
                    txtDiaChi.setText("");
                    txtSoDT.setText("");
                    txtEmail.setText("");
                    txtLuong.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có mã " + manv + ". Không thể xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa Nhân Viên: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
        String manv = txtMaNV.getText();
        String tennv = txtTenNV.getText();
        String gioitinh = txtGioiTinh.getText();
        String diachi = txtDiaChi.getText();
        String sodt = txtSoDT.getText();
        String email = txtEmail.getText();
        String luong = txtLuong.getText();

        try {
            ConnectionDB conn = new ConnectionDB();
            conn.GetConnect();
            Connection connection = conn.GetConnect();

            // Tạo một câu lệnh SQL để gọi thủ tục cập nhật thông tin nhân viên
            String sql = "{ call CapNhatNhanVien(?, ?, ?, ?, ?, ?, ?) }";
            CallableStatement callableStatement = connection.prepareCall(sql);

            // Set các tham số cho thủ tục
            callableStatement.setString(1, manv);
            callableStatement.setString(2, tennv);
            callableStatement.setString(3, gioitinh);
            callableStatement.setString(4, diachi);
            callableStatement.setString(5, sodt);
            callableStatement.setString(6, email);
            callableStatement.setString(7, luong);

            // Thực hiện thủ tục cập nhật
            callableStatement.execute();

            JOptionPane.showMessageDialog(this, "Sửa Nhân Viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Sau khi sửa thành công, làm mới dữ liệu và xoá nội dung của các trường nhập liệu
            btnRefreshNVActionPerformed(evt);
            txtMaNV.setText("");
            txtTenNV.setText("");
            txtGioiTinh.setText("");
            txtDiaChi.setText("");
            txtSoDT.setText("");
            txtEmail.setText("");
            txtLuong.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa Nhân Viên: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMenu;
    private javax.swing.JButton btnRefreshNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_nv;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
